### PR TITLE
Fixed webhooks

### PR DESCRIPTION
**Pull request by ravidshachar**
Previously webhooks didn't work perfectly, when using slider you would get a webhook but without the actual content, and using a card layout you wouldn't get a webhook started at all.

## Description
Modified the webhook format to also send the content of the submission.
Modified and used the SUBMISSION_FINISH_MUTATION in order to set percentageComplete to 1 when submitting a card layout form.

## Motivation and Context
I really wanted to use this project to create dynamic forms for users that start runbooks in the background without writing an app from zero and the webhook functionality was very helpful for that purpose but it didn't work properly as of before, now it works well. figured I might as well open a pull request.

## How Has This Been Tested?
built the container alongside a webhook tester and tried different submissions.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
**doesn't fit the style of the project as is (with the submodules), read the point I've made below**

## Checklist:

- [ ] My code follows the code style of this project.
**In the first commit I merged the submodules into a single repo as I didn't want to fork 3 different repos, so you probably only want the second and third commit**
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by wodka** [comment]
Hi, can you for a fix create the PR in the api repository?

**Comment by wodka** [comment]
just not the way we have the repo here. Would be great though if you can create the 2 separate pull requests in UI and API.

**Comment by wodka** [comment]
Will update the other repositories and still thank you for the commits!

**Comment by wodka** [comment]
@ravidshachar thank you so much! Will check right now!

**Comment by ravidshachar** [comment]
> @ravidshachar thank you so much! Will check right now!

The least I could do! thank you for making this :)

**Pull request closed without merging**
